CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE keyword (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    type VARCHAR(255) CHECK (type IN ('PERSON', 'ORGANIZATION', 'LOCATION', 'EVENT', 'CONCEPT', 'OTHER')),
    PRIMARY KEY (id)
);

CREATE TABLE news_source (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    all_articles_link VARCHAR(255),
    article_link_selector VARCHAR(255),
    title_selector VARCHAR(255),
    content_selector VARCHAR(255),
    date_selector VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE article (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    url VARCHAR(1000) NOT NULL UNIQUE,
    source_id BIGINT NOT NULL,
    category_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    summary TEXT,
    img_links TEXT[],
    views BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    FOREIGN KEY (source_id) REFERENCES news_source(id),
    FOREIGN KEY (category_id) REFERENCES category(id)
);

CREATE TABLE article_keyword (
    article_id BIGINT NOT NULL,
    keyword_id BIGINT NOT NULL,
    PRIMARY KEY (article_id, keyword_id),
    FOREIGN KEY (article_id) REFERENCES article(id),
    FOREIGN KEY (keyword_id) REFERENCES keyword(id)
);

CREATE TABLE article_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    article_id BIGINT NOT NULL,
    action VARCHAR(255) NOT NULL,
    performed_at TIMESTAMP,
    details VARCHAR(1000), -- Store JSON as string
    PRIMARY KEY (id),
    FOREIGN KEY (article_id) REFERENCES article(id)
);

CREATE TABLE change_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    type VARCHAR(255) NOT NULL CHECK (type IN ('ARTICLE_CREATED', 'ARTICLE_DELETED', 'ARTICLE_UPDATED', 'OLD_ARTICLES_CLEANED')),
    entity_type VARCHAR(255) NOT NULL,
    entity_id BIGINT NOT NULL,
    description VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX idx_change_history_entity ON change_history(entity_type, entity_id);
CREATE INDEX idx_change_history_type ON change_history(type);
CREATE INDEX idx_change_history_created_at ON change_history(created_at);

INSERT INTO category (name) VALUES 
('Политика'),
('Экономика'),
('Общество'),
('Наука'),
('Технологии'),
('Спорт'),
('Культура'),
('Происшествия'),
('Здоровье'),
('Образование');

INSERT INTO news_source (name, all_articles_link, article_link_selector, title_selector, content_selector, date_selector) VALUES 
('Т-Журнал', 'https://t-j.ru/news/', '._link_sp8ut_38', '._articleTitle_1jsbf_124', '._articleView_davr3_1', '._dateWrapper_1jsbf_88'); 