CREATE TABLE IF NOT EXISTS public.keyword (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    type VARCHAR(255) CHECK (type IN ('PERSON', 'ORGANIZATION', 'LOCATION', 'EVENT', 'CONCEPT', 'OTHER')),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.article_keyword (
    article_id BIGINT NOT NULL,
    keyword_id BIGINT NOT NULL,
    PRIMARY KEY (article_id, keyword_id),
    FOREIGN KEY (article_id) REFERENCES article(id),
    FOREIGN KEY (keyword_id) REFERENCES keyword(id)
); 